name: tab_benchmark
channels:
  - conda-forge
  - nvidia
dependencies:
  - python=3.11
  - pytorch::pytorch
  - pytorch::pytorch-cuda=12.1
  - lightning
  - matplotlib
  - numpy<2.0
  - pandas
  - scikit-learn
  - scikit-posthocs
  - scipy
  - kaggle
  - py-xgboost
  - lightgbm
  - dask
  - catboost
  - einops
  - mlflow
  - postgresql
  - psycopg2
  - xlrd
  - openpyxl
  - pytest
  - ipykernel
  - ipywidgets
  - dask
  - distributed
  - dask-jobqueue
  - pip
  - optuna
  - seaborn
  - plotly
  - tqdm
  - pip:
    - func-timeout
    - optuna-integration
    - openml
    - -e .
